# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oDKXwhFHCE3Y0gEvoRCMfg3uVkBmuzQX
"""

#!pip install ipywidgets pandas numpy matplotlib seaborn anthropic openai nltk scikit-learn spacy

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import json
import os
import tempfile
import time
from io import BytesIO
import base64

# Импортируем вашу основную программу
from synthetic_resps_improved import (
    RespondentsMarketplace, BankReviewsAnalyzer, FinancialKnowledgeBase,
    CognitiveBiases, EmotionalFactors, LinguisticVariation,
    LifeContextFactors, Inconsistency, EnhancedFinancialRespondent,
    NumpyEncoder
)

# Настройка страницы
st.set_page_config(
    page_title="Симулятор финансовых респондентов",
    page_icon="💰",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Основная функция приложения
def main():
    # CSS стили для современного интерфейса
    st.markdown("""
    <style>
        .main-header {
            font-size: 2.5rem;
            color: #1E88E5;
            text-align: center;
            margin-bottom: 1rem;
        }
        .sub-header {
            font-size: 1.5rem;
            color: #424242;
            margin-top: 2rem;
            margin-bottom: 1rem;
        }
        .card {
            background-color: #f9f9f9;
            border-radius: 8px;
            padding: 20px;
            margin-bottom: 1rem;
            border-left: 5px solid #1E88E5;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        }
        .respondent-card {
            background-color: white;
            border-radius: 8px;
            border: 1px solid #ddd;
            padding: 15px;
            margin-bottom: 15px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.05);
        }
        .success-message {
            padding: 10px;
            background-color: #d4edda;
            color: #155724;
            border-radius: 4px;
            margin-bottom: 10px;
        }
        .error-message {
            padding: 10px;
            background-color: #f8d7da;
            color: #721c24;
            border-radius: 4px;
            margin-bottom: 10px;
        }
        .info-box {
            background-color: #e3f2fd;
            padding: 10px;
            border-radius: 4px;
            margin-bottom: 10px;
        }
        .stTabs [data-baseweb="tab-list"] {
            gap: 2px;
        }
        .stTabs [data-baseweb="tab"] {
            background-color: #f0f2f6;
            border-radius: 4px 4px 0 0;
            padding: 10px 16px;
            margin-right: 2px;
        }
        .stTabs [aria-selected="true"] {
            background-color: #4285F4 !important;
            color: white !important;
        }
    </style>
    """, unsafe_allow_html=True)

    # Заголовок приложения
    st.markdown("<h1 class='main-header'>Симулятор финансовых респондентов</h1>", unsafe_allow_html=True)
    st.markdown("<p style='text-align:center'>Генерация реалистичных ответов от респондентов с разным уровнем финансовой грамотности</p>", unsafe_allow_html=True)

    # Инициализация состояний сессии
    if 'api_keys_set' not in st.session_state:
        st.session_state.api_keys_set = False
    if 'questions_uploaded' not in st.session_state:
        st.session_state.questions_uploaded = False
    if 'reviews_uploaded' not in st.session_state:
        st.session_state.reviews_uploaded = False
    if 'marketplace' not in st.session_state:
        st.session_state.marketplace = None
    if 'respondents' not in st.session_state:
        st.session_state.respondents = []
    if 'questions' not in st.session_state:
        st.session_state.questions = []
    if 'results' not in st.session_state:
        st.session_state.results = None
    if 'generation_complete' not in st.session_state:
        st.session_state.generation_complete = False

    # Создаем вкладки для разных разделов приложения
    tab1, tab2, tab3, tab4 = st.tabs(["📝 Настройка", "👥 Респонденты", "🚀 Генерация", "📊 Результаты"])

    # Вкладка настройки
    with tab1:
        setup_tab()

    # Вкладка респондентов
    with tab2:
        respondents_tab()

    # Вкладка генерации
    with tab3:
        generation_tab()

    # Вкладка результатов
    with tab4:
        results_tab()

# Функция для вкладки настройки
def setup_tab():
    st.markdown("<h2 class='sub-header'>Настройка параметров</h2>", unsafe_allow_html=True)

    with st.expander("API ключи", expanded=not st.session_state.api_keys_set):
        st.markdown("<div class='card'>", unsafe_allow_html=True)
        col1, col2 = st.columns(2)

        with col1:
            claude_api = st.text_input(
                "API ключ Claude (Anthropic)",
                type="password",
                help="Введите API ключ для сервиса Anthropic Claude"
            )

        with col2:
            openai_api = st.text_input(
                "API ключ OpenAI (опционально)",
                type="password",
                help="Опционально: введите API ключ для сервиса OpenAI"
            )

        if st.button("Сохранить API ключи"):
            if claude_api or openai_api:
                st.session_state.api_keys_set = True
                st.session_state.claude_api = claude_api
                st.session_state.openai_api = openai_api
                st.markdown("<div class='success-message'>API ключи успешно сохранены!</div>", unsafe_allow_html=True)
            else:
                st.markdown("<div class='error-message'>Необходимо указать хотя бы один API ключ</div>", unsafe_allow_html=True)
        st.markdown("</div>", unsafe_allow_html=True)

    with st.expander("Загрузка файлов", expanded=not st.session_state.questions_uploaded):
        st.markdown("<div class='card'>", unsafe_allow_html=True)

        st.markdown("### Файл с вопросами (обязательно)")
        questions_file = st.file_uploader(
            "Загрузите Excel файл с вопросами",
            type=["xlsx", "xls"],
            help="Файл должен содержать колонки: question, type, topic, options (опционально)"
        )

        if questions_file is not None:
            with tempfile.NamedTemporaryFile(delete=False, suffix='.xlsx') as tmp:
                tmp.write(questions_file.getvalue())
                tmp_questions_path = tmp.name

            try:
                # Создаем временный маркетплейс для загрузки вопросов
                temp_marketplace = RespondentsMarketplace("temp_key")
                questions = temp_marketplace.load_questions(tmp_questions_path)
                st.session_state.questions = questions
                st.session_state.questions_uploaded = True
                st.session_state.questions_path = tmp_questions_path

                st.markdown(f"<div class='success-message'>Успешно загружено {len(questions)} вопросов</div>", unsafe_allow_html=True)

                # Показываем пример загруженных вопросов
                with st.expander("Предпросмотр загруженных вопросов"):
                    sample_questions = questions[:5] if len(questions) > 5 else questions
                    for q in sample_questions:
                        st.markdown(f"**Вопрос {q['id']}**: {q['text']}")
                        st.markdown(f"Тип: {q['type']}, Тема: {q['topic']}")
                        if q['options']:
                            st.markdown(f"Варианты ответов: {', '.join(q['options'])}")
                        st.markdown("---")

            except Exception as e:
                st.markdown(f"<div class='error-message'>Ошибка при загрузке вопросов: {str(e)}</div>", unsafe_allow_html=True)
                os.unlink(tmp_questions_path)

        st.markdown("### Файл с отзывами о банках (опционально)")
        reviews_file = st.file_uploader(
            "Загрузите Excel файл с отзывами о банках",
            type=["xlsx", "xls"],
            help="Файл должен содержать колонки с отзывами о банках"
        )

        if reviews_file is not None:
            with tempfile.NamedTemporaryFile(delete=False, suffix='.xlsx') as tmp:
                tmp.write(reviews_file.getvalue())
                tmp_reviews_path = tmp.name

            try:
                # Создаем временный анализатор отзывов
                reviews_analyzer = BankReviewsAnalyzer()
                reviews_analyzer.load_reviews(tmp_reviews_path)

                st.session_state.reviews_uploaded = True
                st.session_state.reviews_path = tmp_reviews_path

                st.markdown(f"<div class='success-message'>Успешно загружено отзывов: {len(reviews_analyzer.reviews_data)}</div>", unsafe_allow_html=True)

                # Показываем статистику по отзывам
                with st.expander("Статистика по загруженным отзывам"):
                    bank_info = reviews_analyzer.get_bank_info()
                    st.markdown(f"**Всего отзывов**: {bank_info['total_reviews']}")

                    st.markdown("**Популярные банки**:")
                    for bank, data in list(bank_info['top_banks'].items())[:5]:
                        st.markdown(f"- {bank}: {data['count']} отзывов, средняя оценка: {data['mean']:.2f}")

                    if 'topics' in bank_info:
                        st.markdown("**Основные темы в отзывах**:")
                        for topic, words in list(bank_info['topics'].items())[:3]:
                            st.markdown(f"- {topic}: {', '.join(words[:5])}")

            except Exception as e:
                st.markdown(f"<div class='error-message'>Ошибка при загрузке отзывов: {str(e)}</div>", unsafe_allow_html=True)
                if os.path.exists(tmp_reviews_path):
                    os.unlink(tmp_reviews_path)

        st.markdown("</div>", unsafe_allow_html=True)

    with st.expander("Расширенные настройки"):
        st.markdown("<div class='card'>", unsafe_allow_html=True)

        col1, col2 = st.columns(2)

        with col1:
            api_preference = st.radio(
                "Предпочтительное API",
                options=["claude", "openai", "оба"],
                format_func=lambda x: {"claude": "Claude (по умолчанию)", "openai": "OpenAI", "оба": "Оба API"}[x],
                index=0
            )

            max_workers = st.slider(
                "Количество параллельных потоков",
                min_value=1,
                max_value=10,
                value=3,
                help="Больше потоков ускоряет генерацию, но увеличивает нагрузку на API"
            )

        with col2:
            use_enhanced = st.checkbox(
                "Использовать расширенную генерацию",
                value=True,
                help="Включает когнитивные искажения, эмоциональные факторы и др. для большей реалистичности"
            )

            visualize = st.checkbox(
                "Генерировать визуализации",
                value=True,
                help="Создавать графики и диаграммы по результатам"
            )

            output_format = st.radio(
                "Формат выходного файла",
                options=["excel", "json"],
                format_func=lambda x: {"excel": "Excel (.xlsx)", "json": "JSON (.json)"}[x],
                index=0
            )

        st.text_input(
            "Имя выходного файла",
            value="financial_responses.xlsx" if output_format == "excel" else "financial_responses.json",
            key="output_filename"
        )

        st.markdown("</div>", unsafe_allow_html=True)

# Функция для вкладки респондентов
def respondents_tab():
    st.markdown("<h2 class='sub-header'>Настройка респондентов</h2>", unsafe_allow_html=True)

    num_respondents = st.number_input(
        "Количество респондентов",
        min_value=1,
        max_value=50,
        value=5,
        help="Количество синтетических респондентов для генерации ответов"
    )

    col1, col2 = st.columns([3, 1])

    with col1:
        if st.button("Сгенерировать шаблоны респондентов", disabled=not st.session_state.api_keys_set):
            if not st.session_state.api_keys_set:
                st.markdown("<div class='error-message'>Сначала необходимо настроить API ключи</div>", unsafe_allow_html=True)
            else:
                with st.spinner("Генерация шаблонов респондентов..."):
                    try:
                        # Создаем экземпляр маркетплейса
                        marketplace = RespondentsMarketplace(
                            api_key_claude=st.session_state.claude_api,
                            api_key_openai=st.session_state.openai_api if hasattr(st.session_state, 'openai_api') else None
                        )

                        # Генерируем респондентов
                        respondents = []
                        for i in range(num_respondents):
                            respondent = marketplace.generate_persona()
                            respondent["ID"] = i+1
                            respondents.append(respondent)

                        st.session_state.respondents = respondents
                        st.session_state.marketplace = marketplace

                        st.markdown(f"<div class='success-message'>Успешно создано {len(respondents)} шаблонов респондентов</div>", unsafe_allow_html=True)

                    except Exception as e:
                        st.markdown(f"<div class='error-message'>Ошибка при генерации шаблонов: {str(e)}</div>", unsafe_allow_html=True)

    with col2:
        if st.button("Загрузить из файла", disabled=False):
            st.info("Функция будет доступна в следующей версии")

    # Отображаем карточки респондентов, если они есть
    if hasattr(st.session_state, 'respondents') and st.session_state.respondents:
        st.markdown("<h3>Профили респондентов</h3>", unsafe_allow_html=True)

        for i, respondent in enumerate(st.session_state.respondents):
            with st.expander(f"Респондент #{i+1}: {respondent['Пол']}, {respondent['Возраст']} лет, {respondent['Город']} ({respondent['Регион']})"):
                col1, col2 = st.columns(2)

                with col1:
                    st.markdown("### Демографические данные")
                    st.markdown(f"**Пол**: {respondent['Пол']}")
                    st.markdown(f"**Возраст**: {respondent['Возраст']}")
                    st.markdown(f"**Регион**: {respondent['Регион']}")
                    st.markdown(f"**Город**: {respondent['Город']}")
                    st.markdown(f"**Профессия**: {respondent['Профессия']}")
                    st.markdown(f"**Образование**: {respondent['Образование']}")
                    st.markdown(f"**Семейное положение**: {respondent['Семейное положение']}")
                    st.markdown(f"**Количество детей**: {respondent['Количество детей']}")
                    st.markdown(f"**Доход**: {respondent['Доход']}")
                    st.markdown(f"**Увлечения**: {', '.join(respondent['Увлечения'])}")

                with col2:
                    st.markdown("### Финансовый профиль")
                    fin_profile = respondent['Финансовый профиль']

                    st.markdown(f"**Уровень финансовой грамотности**: {fin_profile['Уровень финансовой грамотности']}")

                    st.markdown("**Используемые финансовые продукты**:")
                    for product, used in fin_profile['Используемые продукты'].items():
                        if used:
                            st.markdown(f"- {product}")

                    st.markdown("**Отношение к финансам**:")
                    for key, value in fin_profile['Отношение к финансам'].items():
                        st.markdown(f"- {key}: {value}")

                    if 'Финансовые цели' in fin_profile:
                        st.markdown(f"**Финансовые цели**: {', '.join(fin_profile['Финансовые цели'])}")

                # Кнопка для редактирования респондента (пока заглушка)
                if st.button(f"Редактировать профиль #{i+1}", key=f"edit_respondent_{i}"):
                    st.info("Функция редактирования будет доступна в следующей версии")

    else:
        st.markdown("<div class='info-box'>Чтобы начать работу, сгенерируйте шаблоны респондентов</div>", unsafe_allow_html=True)

# Функция для вкладки генерации
def generation_tab():
    st.markdown("<h2 class='sub-header'>Генерация ответов</h2>", unsafe_allow_html=True)

    # Проверяем, все ли настройки выполнены
    all_set = st.session_state.api_keys_set and st.session_state.questions_uploaded
    respondents_set = hasattr(st.session_state, 'respondents') and len(st.session_state.respondents) > 0

    if not all_set or not respondents_set:
        st.markdown("<div class='card'>", unsafe_allow_html=True)
        st.markdown("### Необходимо завершить настройку")

        checklist_items = [
            ("✅" if st.session_state.api_keys_set else "❌") + " Настроить API ключи",
            ("✅" if st.session_state.questions_uploaded else "❌") + " Загрузить файл с вопросами",
            ("✅" if respondents_set else "❌") + " Настроить респондентов"
        ]

        for item in checklist_items:
            st.markdown(f"- {item}")

        st.markdown("</div>", unsafe_allow_html=True)
        return

    # Если все настройки выполнены, показываем панель генерации
    st.markdown("<div class='card'>", unsafe_allow_html=True)

    col1, col2 = st.columns([3, 1])

    with col1:
        start_button = st.button(
            "Запустить генерацию ответов",
            disabled=st.session_state.generation_complete,
            use_container_width=True
        )

    with col2:
        if st.session_state.generation_complete:
            reset_button = st.button(
                "Сбросить и начать заново",
                use_container_width=True
            )
            if reset_button:
                st.session_state.generation_complete = False
                st.session_state.results = None
                st.experimental_rerun()

    # Если нажата кнопка генерации
    if start_button:
        with st.spinner("Генерация ответов..."):
            try:
                progress_bar = st.progress(0)
                status_text = st.empty()

                # Здесь будет вызов вашей функции для генерации ответов
                # Для примера я добавлю имитацию прогресса
                total_items = len(st.session_state.respondents) * len(st.session_state.questions)

                # Настройки для генерации
                api_preference = st.session_state.get('api_preference', 'claude')
                max_workers = st.session_state.get('max_workers', 3)
                use_enhanced = st.session_state.get('use_enhanced', True)

                # Подготовка аргументов для запуска генерации
                marketplace = st.session_state.marketplace
                personas = st.session_state.respondents
                questions = st.session_state.questions
                output_format = st.session_state.get('output_format', 'excel')
                output_filename = st.session_state.get('output_filename', 'financial_responses.xlsx')

                # Симуляция генерации для демонстрации
                # В реальном приложении здесь был бы настоящий вызов функции генерации
                for i in range(100):
                    # Обновляем прогресс
                    progress = min(i/99, 1.0)
                    progress_bar.progress(progress)

                    # Эмуляция текущего прогресса
                    current_item = int(progress * total_items)
                    status_text.text(f"Обработано {current_item}/{total_items} ответов...")

                    time.sleep(0.05)

                # После успешной генерации
                st.session_state.generation_complete = True

                # Сохраняем результаты (тестовые данные)
                st.session_state.results = {
                    "personas": personas,
                    "questions": questions,
                    "answers": [{"id": i, "persona_id": p["ID"],
                                "question": q,
                                "text": f"Сгенерированный ответ от респондента #{p['ID']} на вопрос {q['id']}"}
                                for i, (p, q) in enumerate([(p, q) for p in personas for q in questions])],
                    "report": {
                        "Общая статистика": {
                            "Количество респондентов": len(personas),
                            "Количество вопросов": len(questions),
                            "Количество ответов": total_items
                        }
                    }
                }

                st.markdown("<div class='success-message'>Генерация успешно завершена! Перейдите на вкладку Результаты для просмотра.</div>", unsafe_allow_html=True)

            except Exception as e:
                st.markdown(f"<div class='error-message'>Ошибка при генерации ответов: {str(e)}</div>", unsafe_allow_html=True)

    st.markdown("</div>", unsafe_allow_html=True)

# Функция для вкладки результатов
def results_tab():
    st.markdown("<h2 class='sub-header'>Результаты и анализ</h2>", unsafe_allow_html=True)

    if not hasattr(st.session_state, 'results') or not st.session_state.results:
        st.markdown("<div class='info-box'>Сначала выполните генерацию ответов на вкладке Генерация</div>", unsafe_allow_html=True)
        return

    results = st.session_state.results

    # Отображаем основную статистику
    st.markdown("<div class='card'>", unsafe_allow_html=True)
    st.markdown("### Общая статистика")

    col1, col2, col3 = st.columns(3)
    with col1:
        st.metric("Респондентов", results["report"]["Общая статистика"]["Количество респондентов"])
    with col2:
        st.metric("Вопросов", results["report"]["Общая статистика"]["Количество вопросов"])
    with col3:
        st.metric("Всего ответов", results["report"]["Общая статистика"]["Количество ответов"])

    st.markdown("</div>", unsafe_allow_html=True)

    # Создаем вкладки для разных видов результатов
    result_tabs = st.tabs(["Примеры ответов", "Демография", "Анализ", "Экспорт"])

    # Вкладка с примерами ответов
    with result_tabs[0]:
        st.markdown("### Примеры сгенерированных ответов")

        # Фильтры для отображения ответов
        col1, col2 = st.columns(2)
        with col1:
            selected_respondent = st.selectbox(
                "Фильтр по респонденту",
                options=["Все"] + [f"#{p['ID']}: {p['Пол']}, {p['Возраст']} лет" for p in results["personas"]]
            )

        with col2:
            selected_question = st.selectbox(
                "Фильтр по вопросу",
                options=["Все"] + [f"#{q['id']}: {q['text'][:50]}..." for q in results["questions"]]
            )

        # Отображаем ответы согласно выбранным фильтрам
        answers_to_show = results["answers"]

        if selected_respondent != "Все":
            respondent_id = int(selected_respondent.split(":")[0].replace("#", ""))
            answers_to_show = [a for a in answers_to_show if a["persona_id"] == respondent_id]

        if selected_question != "Все":
            question_id = int(selected_question.split(":")[0].replace("#", ""))
            answers_to_show = [a for a in answers_to_show if a["question"]["id"] == question_id]

        # Ограничиваем количество отображаемых ответов
        answers_to_show = answers_to_show[:10] if len(answers_to_show) > 10 else answers_to_show

        for answer in answers_to_show:
            persona = next((p for p in results["personas"] if p["ID"] == answer["persona_id"]), None)
            if not persona:
                continue

            with st.expander(f"Респондент #{persona['ID']}: {persona['Пол']}, {persona['Возраст']} лет - Вопрос #{answer['question']['id']}"):
                st.markdown(f"**Вопрос**: {answer['question']['text']}")
                st.markdown(f"**Ответ**:")
                st.markdown(f"<div class='respondent-card'>{answer['text']}</div>", unsafe_allow_html=True)

                literacy_level = persona['Финансовый профиль']['Уровень финансовой грамотности']
                st.markdown(f"*Уровень финансовой грамотности респондента: {literacy_level}*")

    # Вкладка с демографией
    with result_tabs[1]:
        st.markdown("### Демографический анализ респондентов")

        # Создаем DataFrame для анализа
        demo_data = []
        for p in results["personas"]:
            row = {
                "ID": p["ID"],
                "Пол": p["Пол"],
                "Возраст": p["Возраст"],
                "Регион": p["Регион"],
                "Образование": p["Образование"],
                "Финансовая грамотность": p["Финансовый профиль"]["Уровень финансовой грамотности"]
            }
            demo_data.append(row)

        df = pd.DataFrame(demo_data)

        # Визуализации демографии
        col1, col2 = st.columns(2)

        with col1:
            st.markdown("#### Распределение по полу")
            gender_counts = df["Пол"].value_counts()
            fig1, ax1 = plt.subplots()
            ax1.pie(gender_counts, labels=gender_counts.index, autopct='%1.1f%%', startangle=90)
            ax1.axis('equal')
            st.pyplot(fig1)

        with col2:
            st.markdown("#### Распределение по возрасту")
            fig2, ax2 = plt.subplots()
            ax2.hist(df["Возраст"], bins=10, edgecolor='black')
            ax2.set_xlabel("Возраст")
            ax2.set_ylabel("Количество")
            st.pyplot(fig2)

        col3, col4 = st.columns(2)

        with col3:
            st.markdown("#### Распределение по уровню финансовой грамотности")
            fig3, ax3 = plt.subplots()
            literacy_order = ["отсутствие знаний", "начинающий", "средний", "продвинутый", "эксперт"]
            literacy_counts = df["Финансовая грамотность"].value_counts().reindex(literacy_order).fillna(0)
            ax3.bar(literacy_counts.index, literacy_counts.values)
            ax3.set_xticklabels(literacy_counts.index, rotation=45, ha="right")
            st.pyplot(fig3)

        with col4:
            st.markdown("#### Распределение по регионам")
            fig4, ax4 = plt.subplots()
            region_counts = df["Регион"].value_counts().head(5)
            ax4.bar(region_counts.index, region_counts.values)
            ax4.set_xticklabels(region_counts.index, rotation=45, ha="right")
            st.pyplot(fig4)

    # Вкладка с анализом
    with result_tabs[2]:
        st.markdown("### Анализ ответов")
        st.info("Полный анализ будет доступен в следующей версии")

    # Вкладка с экспортом
    with result_tabs[3]:
        st.markdown("### Экспорт результатов")

        col1, col2 = st.columns(2)

        with col1:
            if st.button("Экспорт в Excel"):
                # Создаем буфер для записи Excel файла
                output = BytesIO()

                # Создаем Excel-writer
                with pd.ExcelWriter(output, engine='openpyxl') as writer:
                    # Экспортируем данные на разные листы

                    # Лист с респондентами
                    persona_rows = []
                    for p in results["personas"]:
                        row = {
                            "ID": p["ID"],
                            "Пол": p["Пол"],
                            "Возраст": p["Возраст"],
                            "Регион": p["Регион"],
                            "Город": p["Город"],
                            "Образование": p["Образование"],
                            "Финансовая грамотность": p["Финансовый профиль"]["Уровень финансовой грамотности"]
                        }
                        persona_rows.append(row)

                    pd.DataFrame(persona_rows).to_excel(writer, sheet_name='Респонденты', index=False)

                    # Лист с вопросами
                    question_rows = []
                    for q in results["questions"]:
                        row = {
                            "ID": q["id"],
                            "Вопрос": q["text"],
                            "Тип": q["type"],
                            "Тема": q["topic"]
                        }
                        question_rows.append(row)

                    pd.DataFrame(question_rows).to_excel(writer, sheet_name='Вопросы', index=False)

                    # Лист с ответами
                    answer_rows = []
                    for a in results["answers"]:
                        row = {
                            "ID ответа": a["id"],
                            "ID респондента": a["persona_id"],
                            "ID вопроса": a["question"]["id"],
                            "Вопрос": a["question"]["text"],
                            "Ответ": a["text"]
                        }
                        answer_rows.append(row)

                    pd.DataFrame(answer_rows).to_excel(writer, sheet_name='Ответы', index=False)

                # Создаем ссылку для скачивания
                b64 = base64.b64encode(output.getvalue()).decode()
                href = f'<a href="data:application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;base64,{b64}" download="financial_responses.xlsx">Скачать Excel файл</a>'
                st.markdown(href, unsafe_allow_html=True)

        with col2:
            if st.button("Экспорт в JSON"):
                # Сериализуем результаты в JSON
                json_str = json.dumps(results, ensure_ascii=False, indent=2, cls=NumpyEncoder)

                # Создаем ссылку для скачивания
                b64 = base64.b64encode(json_str.encode()).decode()
                href = f'<a href="data:application/json;base64,{b64}" download="financial_responses.json">Скачать JSON файл</a>'
                st.markdown(href, unsafe_allow_html=True)

# Запуск приложения
if __name__ == "__main__":
    main()
